-- EF Architects and Engineers Consulting PLC
-- Database Migration Script

-- Create custom enums if they do not exist
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'user_role') THEN
    CREATE TYPE user_role AS ENUM ('engineer', 'admin', 'dgm');
  END IF;
  
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'approval_status') THEN
    CREATE TYPE approval_status AS ENUM ('Pending', 'Approved', 'Returned');
  END IF;
  
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'direction_enum') THEN
    CREATE TYPE direction_enum AS ENUM ('Incoming', 'Outgoing');
  END IF;
  
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'correspondence_category') THEN
    CREATE TYPE correspondence_category AS ENUM ('NOC', 'General', 'RFI', 'EOT Claim', 'Variation', 'Payment');
  END IF;
  
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'bond_type_enum') THEN
    CREATE TYPE bond_type_enum AS ENUM ('Advance Payment Bond', 'Performance Bond');
  END IF;
  
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'bond_status_enum') THEN
    CREATE TYPE bond_status_enum AS ENUM ('Active', 'Expired', 'Released');
  END IF;
  
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'eot_status_enum') THEN
    CREATE TYPE eot_status_enum AS ENUM ('Approved', 'Rejected', 'Pending', 'Under Review');
  END IF;
  
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'eot_status_alert_enum') THEN
    CREATE TYPE eot_status_alert_enum AS ENUM ('OK', 'Nearly Expired', 'Expired');
  END IF;
  
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'performance_level_enum') THEN
    CREATE TYPE performance_level_enum AS ENUM ('Outstanding', 'Very Good', 'Good', 'Satisfactory', 'Needs Improvement');
  END IF;
END
$$;

-- 1. employees TABLE
CREATE TABLE IF NOT EXISTS employees (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  full_name VARCHAR(255) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  department VARCHAR(255) DEFAULT 'Procurement and Contract Administration' NOT NULL,
  role user_role DEFAULT 'engineer' NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- 2. daily_work_logs TABLE
CREATE TABLE IF NOT EXISTS daily_work_logs (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  employee_id UUID REFERENCES employees(id) ON DELETE CASCADE NOT NULL,
  log_date DATE NOT NULL,
  day_of_week VARCHAR(50),
  assigned_tasks TEXT NOT NULL,
  actual_work_done TEXT NOT NULL,
  hours_worked NUMERIC(4,2) NOT NULL,
  actual_working_hour NUMERIC(4,2) NOT NULL,
  completion_percentage NUMERIC(3,2) NOT NULL CHECK (completion_percentage >= 0.00 AND completion_percentage <= 1.00),
  done_at_home BOOLEAN DEFAULT FALSE NOT NULL,
  remark TEXT,
  office_entrance_time TIME,
  office_leave_time TIME,
  approval_status approval_status DEFAULT 'Pending' NOT NULL,
  head_comments TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- 3. correspondence_register TABLE
CREATE TABLE IF NOT EXISTS correspondence_register (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  letter_ref_no VARCHAR(100) UNIQUE NOT NULL,
  date_logged DATE NOT NULL,
  direction direction_enum NOT NULL,
  counterparty VARCHAR(255) NOT NULL,
  subject TEXT NOT NULL,
  category correspondence_category NOT NULL,
  response_required BOOLEAN DEFAULT FALSE NOT NULL,
  response_due_date DATE,
  linked_response_ref VARCHAR(100),
  response_sent_date DATE,
  status VARCHAR(50) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- 4. project_bonds TABLE
CREATE TABLE IF NOT EXISTS project_bonds (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  employer_name VARCHAR(255) NOT NULL,
  project_name TEXT NOT NULL,
  contractor_name VARCHAR(255) NOT NULL,
  bond_type bond_type_enum NOT NULL,
  issue_date DATE,
  expiry_date DATE NOT NULL,
  amount NUMERIC(15,2),
  status bond_status_enum DEFAULT 'Active' NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- 5. eot_tracker TABLE
CREATE TABLE IF NOT EXISTS eot_tracker (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  client_name VARCHAR(255) NOT NULL,
  project_name TEXT NOT NULL,
  contractor_name VARCHAR(255) NOT NULL,
  eot_number INT NOT NULL,
  days_approved INT NOT NULL,
  revised_completion_date DATE NOT NULL,
  status eot_status_enum DEFAULT 'Pending' NOT NULL,
  reason_for_eot TEXT NOT NULL,
  eot_status_alert eot_status_alert_enum DEFAULT 'OK' NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- 6. performance_evaluations TABLE
CREATE TABLE IF NOT EXISTS performance_evaluations (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  employee_id UUID REFERENCES employees(id) ON DELETE CASCADE NOT NULL,
  evaluation_period_start DATE NOT NULL,
  evaluation_period_end DATE NOT NULL,
  tech_competence_score NUMERIC(5,2) NOT NULL CHECK (tech_competence_score >= 0.00 AND tech_competence_score <= 100.00),
  productivity_score NUMERIC(5,2) NOT NULL CHECK (productivity_score >= 0.00 AND productivity_score <= 100.00),
  punctuality_score NUMERIC(5,2) NOT NULL CHECK (punctuality_score >= 0.00 AND punctuality_score <= 100.00),
  communication_score NUMERIC(5,2) NOT NULL CHECK (communication_score >= 0.00 AND communication_score <= 100.00),
  reporting_score NUMERIC(5,2) NOT NULL CHECK (reporting_score >= 0.00 AND reporting_score <= 100.00),
  adaptability_score NUMERIC(5,2) NOT NULL CHECK (adaptability_score >= 0.00 AND adaptability_score <= 100.00),
  total_score NUMERIC(5,2),
  performance_level performance_level_enum,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- Enable Row Level Security (RLS) on all tables
ALTER TABLE employees ENABLE ROW LEVEL SECURITY;
ALTER TABLE daily_work_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE correspondence_register ENABLE ROW LEVEL SECURITY;
ALTER TABLE project_bonds ENABLE ROW LEVEL SECURITY;
ALTER TABLE eot_tracker ENABLE ROW LEVEL SECURITY;
ALTER TABLE performance_evaluations ENABLE ROW LEVEL SECURITY;

-- ────────────────────────────────────────────────────────
-- POLICIES
-- ────────────────────────────────────────────────────────

-- Employees policies
DROP POLICY IF EXISTS "employees_select_policy" ON employees;
CREATE POLICY "employees_select_policy" ON employees
  FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "employees_all_policy" ON employees;
CREATE POLICY "employees_all_policy" ON employees
  FOR ALL TO authenticated USING (
    id = auth.uid() OR role = 'admin' OR role = 'dgm'
  );

-- Daily Work Logs policies
DROP POLICY IF EXISTS "logs_select_policy" ON daily_work_logs;
CREATE POLICY "logs_select_policy" ON daily_work_logs
  FOR SELECT TO authenticated USING (
    employee_id = auth.uid() OR 
    EXISTS (SELECT 1 FROM employees WHERE id = auth.uid() AND (role = 'admin' OR role = 'dgm'))
  );

DROP POLICY IF EXISTS "logs_all_policy" ON daily_work_logs;
CREATE POLICY "logs_all_policy" ON daily_work_logs
  FOR ALL TO authenticated USING (
    employee_id = auth.uid() OR
    EXISTS (SELECT 1 FROM employees WHERE id = auth.uid() AND (role = 'admin' OR role = 'dgm'))
  );

-- Correspondence policies
DROP POLICY IF EXISTS "correspondence_select_policy" ON correspondence_register;
CREATE POLICY "correspondence_select_policy" ON correspondence_register
  FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "correspondence_all_policy" ON correspondence_register;
CREATE POLICY "correspondence_all_policy" ON correspondence_register
  FOR ALL TO authenticated USING (
    EXISTS (SELECT 1 FROM employees WHERE id = auth.uid() AND (role = 'admin' OR role = 'dgm'))
  );

-- Project Bonds policies
DROP POLICY IF EXISTS "bonds_select_policy" ON project_bonds;
CREATE POLICY "bonds_select_policy" ON project_bonds
  FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "bonds_all_policy" ON project_bonds;
CREATE POLICY "bonds_all_policy" ON project_bonds
  FOR ALL TO authenticated USING (
    EXISTS (SELECT 1 FROM employees WHERE id = auth.uid() AND (role = 'admin' OR role = 'dgm'))
  );

-- EOT Tracker policies
DROP POLICY IF EXISTS "eot_select_policy" ON eot_tracker;
CREATE POLICY "eot_select_policy" ON eot_tracker
  FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "eot_all_policy" ON eot_tracker;
CREATE POLICY "eot_all_policy" ON eot_tracker
  FOR ALL TO authenticated USING (
    EXISTS (SELECT 1 FROM employees WHERE id = auth.uid() AND (role = 'admin' OR role = 'dgm'))
  );

-- Performance Evaluations policies
DROP POLICY IF EXISTS "eval_select_policy" ON performance_evaluations;
CREATE POLICY "eval_select_policy" ON performance_evaluations
  FOR SELECT TO authenticated USING (
    employee_id = auth.uid() OR
    EXISTS (SELECT 1 FROM employees WHERE id = auth.uid() AND (role = 'admin' OR role = 'dgm'))
  );

DROP POLICY IF EXISTS "eval_all_policy" ON performance_evaluations;
CREATE POLICY "eval_all_policy" ON performance_evaluations
  FOR ALL TO authenticated USING (
    EXISTS (SELECT 1 FROM employees WHERE id = auth.uid() AND (role = 'admin' OR role = 'dgm'))
  );

-- ────────────────────────────────────────────────────────
-- TRIGGERS & FUNCTIONS
-- ────────────────────────────────────────────────────────

-- 0. Auto-populate day_of_week on daily_work_logs
CREATE OR REPLACE FUNCTION set_day_of_week()
RETURNS TRIGGER AS $$
BEGIN
  NEW.day_of_week := to_char(NEW.log_date, 'FMDay');
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_set_day_of_week ON daily_work_logs;
CREATE TRIGGER trg_set_day_of_week
  BEFORE INSERT OR UPDATE ON daily_work_logs
  FOR EACH ROW
  EXECUTE FUNCTION set_day_of_week();

-- 1. Performance Evaluation automated scoring and ranking
CREATE OR REPLACE FUNCTION calculate_performance_eval()
RETURNS TRIGGER AS $$
BEGIN
  -- Score formula: Tech*0.40 + Prod*0.30 + Punc*0.10 + Comm*0.05 + Rep*0.05 + Adapt*0.10
  NEW.total_score := (NEW.tech_competence_score * 0.40) +
                     (NEW.productivity_score * 0.30) +
                     (NEW.punctuality_score * 0.10) +
                     (NEW.communication_score * 0.05) +
                     (NEW.reporting_score * 0.05) +
                     (NEW.adaptability_score * 0.10);

  -- Determine tier
  IF NEW.total_score >= 90.00 THEN
    NEW.performance_level := 'Outstanding';
  ELSIF NEW.total_score >= 80.00 THEN
    NEW.performance_level := 'Very Good';
  ELSIF NEW.total_score >= 70.00 THEN
    NEW.performance_level := 'Good';
  ELSIF NEW.total_score >= 60.00 THEN
    NEW.performance_level := 'Satisfactory';
  ELSE
    NEW.performance_level := 'Needs Improvement';
  END IF;
  
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_calculate_performance_eval ON performance_evaluations;
CREATE TRIGGER trg_calculate_performance_eval
  BEFORE INSERT OR UPDATE ON performance_evaluations
  FOR EACH ROW
  EXECUTE FUNCTION calculate_performance_eval();

-- 2. Correspondence Register automated response due date and status
CREATE OR REPLACE FUNCTION handle_correspondence_status()
RETURNS TRIGGER AS $$
BEGIN
  -- Set response_due_date = date_logged + 7 days if response is required and not manually set
  IF NEW.response_required = TRUE THEN
    IF NEW.response_due_date IS NULL THEN
      NEW.response_due_date := NEW.date_logged + INTERVAL '7 days';
    END IF;
  ELSE
    NEW.response_due_date := NULL;
  END IF;

  -- Establish status
  IF NEW.response_required = FALSE THEN
    NEW.status := 'Not Required';
  ELSIF NEW.response_sent_date IS NOT NULL THEN
    NEW.status := 'Closed';
  ELSIF NEW.response_due_date < CURRENT_DATE THEN
    NEW.status := 'Overdue';
  ELSE
    NEW.status := 'Open';
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_handle_correspondence_status ON correspondence_register;
CREATE TRIGGER trg_handle_correspondence_status
  BEFORE INSERT OR UPDATE ON correspondence_register
  FOR EACH ROW
  EXECUTE FUNCTION handle_correspondence_status();

-- ────────────────────────────────────────────────────────
-- ADDITIONAL TABLES (Projects & Employee Assignments)
-- Run these manually in Supabase SQL Editor if not yet applied
-- ────────────────────────────────────────────────────────

-- Step 1: Extend the user_role enum to include 'registrar'
-- (Must be run BEFORE creating tables that reference it in policies)
ALTER TYPE user_role ADD VALUE IF NOT EXISTS 'registrar';

-- Step 2: Add missing 'active' column to employees table (if not already present)
ALTER TABLE employees ADD COLUMN IF NOT EXISTS active BOOLEAN DEFAULT TRUE NOT NULL;

-- Step 3: Optionally update any existing employee you want to be a registrar:
-- UPDATE employees SET role = 'registrar' WHERE email = 'registrar@example.com';

-- 7. projects TABLE
CREATE TABLE IF NOT EXISTS projects (
  code VARCHAR(50) PRIMARY KEY,
  name TEXT NOT NULL,
  active BOOLEAN DEFAULT TRUE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

ALTER TABLE projects ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "projects_select_policy" ON projects;
CREATE POLICY "projects_select_policy" ON projects
  FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "projects_all_policy" ON projects;
CREATE POLICY "projects_all_policy" ON projects
  FOR ALL TO authenticated USING (
    EXISTS (SELECT 1 FROM employees WHERE id = auth.uid() AND (role = 'admin' OR role = 'dgm' OR role = 'registrar'))
  );

-- 8. employee_project_assignments TABLE
CREATE TABLE IF NOT EXISTS employee_project_assignments (
  employee_id UUID REFERENCES employees(id) ON DELETE CASCADE NOT NULL,
  project_code VARCHAR(50) REFERENCES projects(code) ON DELETE CASCADE NOT NULL,
  assigned_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  PRIMARY KEY (employee_id, project_code)
);

ALTER TABLE employee_project_assignments ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "assignments_select_policy" ON employee_project_assignments;
CREATE POLICY "assignments_select_policy" ON employee_project_assignments
  FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "assignments_all_policy" ON employee_project_assignments;
CREATE POLICY "assignments_all_policy" ON employee_project_assignments
  FOR ALL TO authenticated USING (
    EXISTS (SELECT 1 FROM employees WHERE id = auth.uid() AND (role = 'admin' OR role = 'dgm' OR role = 'registrar'))
  );
