-- ============================================================
-- EF Architects & Engineers Consulting PLC
-- Migration: Immediate-Lock Policy for daily_work_logs
-- Run this entire script in Supabase SQL Editor (one-shot)
-- ============================================================

-- ────────────────────────────────────────────────────────────
-- STEP 1: Postgres trigger function — blocks ALL UPDATE and
--         DELETE on daily_work_logs once a row exists.
--         The service-role key bypasses RLS, but triggers fire
--         at the storage engine level and CANNOT be bypassed.
-- ────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION block_task_alterations()
RETURNS TRIGGER AS $$
BEGIN
  RAISE EXCEPTION
    'Submission Locked: Once a daily task log is saved it cannot be modified or deleted. '
    'Row id=%, employee_id=%, log_date=%.',
    OLD.id, OLD.employee_id, OLD.log_date
    USING ERRCODE = 'restrict_violation';
  RETURN NULL;
END;
$$ LANGUAGE plpgsql
   SECURITY DEFINER  -- runs as owner, so even service-role calls are blocked
   SET search_path = public;

-- Drop and recreate so the trigger is idempotent (safe to re-run)
DROP TRIGGER IF EXISTS lock_submitted_tasks ON daily_work_logs;

CREATE TRIGGER lock_submitted_tasks
  BEFORE UPDATE OR DELETE ON daily_work_logs
  FOR EACH ROW
  EXECUTE FUNCTION block_task_alterations();

-- ────────────────────────────────────────────────────────────
-- STEP 2: RLS policies — employees (role = 'engineer') get
--         INSERT + SELECT only. Admin/DGM retain SELECT only
--         (they can never mutate rows either — the trigger
--         covers that for everyone, RLS adds a declarative
--         second layer for engineers specifically).
-- ────────────────────────────────────────────────────────────

-- 2a. SELECT — own rows for engineers, all rows for admin/dgm
DROP POLICY IF EXISTS "logs_select_policy" ON daily_work_logs;
CREATE POLICY "logs_select_policy" ON daily_work_logs
  FOR SELECT TO authenticated
  USING (
    employee_id = auth.uid()
    OR EXISTS (
      SELECT 1 FROM employees
      WHERE id = auth.uid()
        AND role IN ('admin', 'dgm')
    )
  );

-- 2b. INSERT — employees may only insert rows belonging to themselves
DROP POLICY IF EXISTS "logs_insert_policy" ON daily_work_logs;
CREATE POLICY "logs_insert_policy" ON daily_work_logs
  FOR INSERT TO authenticated
  WITH CHECK (employee_id = auth.uid());

-- 2c. UPDATE — explicitly DENIED for all authenticated users via RLS.
--     (Trigger is the hard backstop; this policy makes the intent
--      crystal-clear and is enforced when anon-key clients are used.)
DROP POLICY IF EXISTS "logs_update_policy" ON daily_work_logs;
-- No CREATE POLICY for UPDATE — absence of an UPDATE policy means
-- the default-deny for RLS applies automatically for any client
-- using the anon/service role without SECURITY DEFINER bypass.
-- We add an explicit DENY policy for clarity:
CREATE POLICY "logs_update_deny_policy" ON daily_work_logs
  FOR UPDATE TO authenticated
  USING (false)          -- no row satisfies this → all UPDATEs rejected
  WITH CHECK (false);

-- 2d. DELETE — explicitly DENIED for all authenticated users via RLS.
DROP POLICY IF EXISTS "logs_delete_policy" ON daily_work_logs;
CREATE POLICY "logs_delete_deny_policy" ON daily_work_logs
  FOR DELETE TO authenticated
  USING (false);

-- 2e. Remove the old catch-all "logs_all_policy" that granted UPDATE/DELETE
DROP POLICY IF EXISTS "logs_all_policy" ON daily_work_logs;

-- ────────────────────────────────────────────────────────────
-- STEP 3: Admin / DGM approval workflow exception
--   Approving a log (setting approval_status, head_comments)
--   is intentionally NOT allowed to mutate the employee's
--   submitted content fields. The trigger blocks all UPDATEs
--   unconditionally, so the approval workflow must use a
--   SEPARATE audit / review table (see daily_work_log_reviews
--   below) instead of mutating the original row. This preserves
--   the immutability guarantee end-to-end.
-- ────────────────────────────────────────────────────────────

-- Separate approval-review table (append-only for admin actions)
CREATE TABLE IF NOT EXISTS daily_work_log_reviews (
  id              BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  log_id          BIGINT NOT NULL REFERENCES daily_work_logs(id) ON DELETE CASCADE,
  reviewed_by     UUID   NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
  approval_status approval_status NOT NULL DEFAULT 'Pending',
  head_comments   TEXT,
  reviewed_at     TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

ALTER TABLE daily_work_log_reviews ENABLE ROW LEVEL SECURITY;

-- Admins/DGM can insert reviews
DROP POLICY IF EXISTS "reviews_insert_policy" ON daily_work_log_reviews;
CREATE POLICY "reviews_insert_policy" ON daily_work_log_reviews
  FOR INSERT TO authenticated
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM employees
      WHERE id = auth.uid()
        AND role IN ('admin', 'dgm')
    )
  );

-- Everyone can read reviews
DROP POLICY IF EXISTS "reviews_select_policy" ON daily_work_log_reviews;
CREATE POLICY "reviews_select_policy" ON daily_work_log_reviews
  FOR SELECT TO authenticated
  USING (true);

-- Nobody can update or delete review records (append-only audit log)
DROP POLICY IF EXISTS "reviews_update_deny" ON daily_work_log_reviews;
CREATE POLICY "reviews_update_deny" ON daily_work_log_reviews
  FOR UPDATE TO authenticated
  USING (false)
  WITH CHECK (false);

DROP POLICY IF EXISTS "reviews_delete_deny" ON daily_work_log_reviews;
CREATE POLICY "reviews_delete_deny" ON daily_work_log_reviews
  FOR DELETE TO authenticated
  USING (false);

-- ────────────────────────────────────────────────────────────
-- STEP 4: Convenience view that joins the latest review onto
--         each log so the API can return approval_status
--         without mutating daily_work_logs.
-- ────────────────────────────────────────────────────────────
CREATE OR REPLACE VIEW daily_work_logs_with_review AS
SELECT
  l.*,
  r.approval_status  AS review_status,
  r.head_comments    AS review_comments,
  r.reviewed_by,
  r.reviewed_at
FROM daily_work_logs l
LEFT JOIN LATERAL (
  SELECT approval_status, head_comments, reviewed_by, reviewed_at
  FROM   daily_work_log_reviews
  WHERE  log_id = l.id
  ORDER  BY reviewed_at DESC
  LIMIT  1
) r ON true;

-- ============================================================
-- END OF MIGRATION
-- ============================================================
-- Summary of guarantees after this migration:
--   1. Postgres trigger (SECURITY DEFINER, pre-storage engine)
--      fires BEFORE UPDATE OR DELETE on every row — no client,
--      no service-role call, no internal DB operation can
--      mutate or remove a submitted log.
--   2. RLS policies (INSERT + SELECT for engineers, deny UPDATE
--      and DELETE for all authenticated roles) add a
--      declarative second layer at the query planner level.
--   3. Approval workflow moved to daily_work_log_reviews
--      (append-only) so admins can record decisions without
--      touching the immutable source rows.
-- ============================================================
